/**
 * Color Palettes
 *
 * This file contains color palettes for particle groups.
 * Each palette consists of 5 colors, one for each particle role (CORE, CONTROL, MOVEMENT, DEFENSE, ATTACK).
 *
 * IMPORTANT: This file is auto-generated. Do not edit directly.
 * Generated by color-palette-generator.ps1
 */

/**
 * Color interface
 */
export interface Color {
  r: number;
  g: number;
  b: number;
}

/**
 * Palette interface
 */
export interface Palette {
  name: string;
  category: string;
  description: string;
  CORE: Color;
  CONTROL: Color;
  MOVEMENT: Color;
  DEFENSE: Color;
  ATTACK: Color;
}

/**
 * Color palettes
 */
export const COLOR_PALETTES: Record<string, Palette> = {  11: {
    name: "Natural Themes 11",
    category: "Natural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.827450980392157, g: 0.619607843137255, b: 0.968627450980392 },
    CONTROL: { r: 0.968627450980392, g: 0.619607843137255, b: 0.933333333333333 },
    MOVEMENT: { r: 0.654901960784314, g: 0.619607843137255, b: 0.968627450980392 },
    DEFENSE: { r: 0.968627450980392, g: 0.827450980392157, b: 0.619607843137255 },
    ATTACK: { r: 0.172549019607843, g: 0.380392156862745, b: 0.0313725490196078 }
  },
  7: {
    name: "Cultural Themes 7",
    category: "Cultural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.0313725490196078, g: 0.725490196078431, b: 0.83921568627451 },
    CONTROL: { r: 0.0313725490196078, g: 0.32156862745098, b: 0.83921568627451 },
    MOVEMENT: { r: 0.0313725490196078, g: 0.83921568627451, b: 0.549019607843137 },
    DEFENSE: { r: 0.83921568627451, g: 0.0313725490196078, b: 0.725490196078431 },
    ATTACK: { r: 0.968627450980392, g: 0.274509803921569, b: 0.16078431372549 }
  },
  38: {
    name: "Digital Ecosystem 38",
    category: "Digital Ecosystem",
    description: "Generated palette based on color theory",
    CORE: { r: 0.298039215686275, g: 0.776470588235294, b: 0.258823529411765 },
    CONTROL: { r: 0.258823529411765, g: 0.776470588235294, b: 0.47843137254902 },
    MOVEMENT: { r: 0.556862745098039, g: 0.776470588235294, b: 0.258823529411765 },
    DEFENSE: { r: 0.258823529411765, g: 0.298039215686275, b: 0.776470588235294 },
    ATTACK: { r: 0.701960784313725, g: 0.223529411764706, b: 0.741176470588235 }
  },
  bitcoinClassic: {
    name: "Bitcoin Classic",
    category: "Bitcoin-Inspired",
    description: "Generated palette based on color theory",
    CORE: { r: 0.968627450980392, g: 0.576470588235294, b: 0.101960784313725 },
    CONTROL: { r: 0.925490196078431, g: 0.968627450980392, b: 0.101960784313725 },
    MOVEMENT: { r: 0.968627450980392, g: 0.145098039215686, b: 0.101960784313725 },
    DEFENSE: { r: 0.101960784313725, g: 0.968627450980392, b: 0.576470588235294 },
    ATTACK: { r: 0.0313725490196078, g: 0.423529411764706, b: 0.898039215686275 }
  },
  12: {
    name: "Seasonal Themes 12",
    category: "Seasonal Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.262745098039216, g: 0.368627450980392, b: 0.611764705882353 },
    CONTROL: { r: 0.333333333333333, g: 0.262745098039216, b: 0.611764705882353 },
    MOVEMENT: { r: 0.262745098039216, g: 0.541176470588235, b: 0.611764705882353 },
    DEFENSE: { r: 0.611764705882353, g: 0.262745098039216, b: 0.368627450980392 },
    ATTACK: { r: 0.737254901960784, g: 0.631372549019608, b: 0.388235294117647 }
  },
  10: {
    name: "Digital Ecosystem 10",
    category: "Digital Ecosystem",
    description: "Generated palette based on color theory",
    CORE: { r: 0.172549019607843, g: 0.976470588235294, b: 0.811764705882353 },
    CONTROL: { r: 0.172549019607843, g: 0.741176470588235, b: 0.976470588235294 },
    MOVEMENT: { r: 0.172549019607843, g: 0.976470588235294, b: 0.407843137254902 },
    DEFENSE: { r: 0.811764705882353, g: 0.172549019607843, b: 0.976470588235294 },
    ATTACK: { r: 0.827450980392157, g: 0.0235294117647059, b: 0.188235294117647 }
  },
  seasonalSpring: {
    name: "Seasonal Spring",
    category: "Seasonal Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.564705882352941, g: 0.933333333333333, b: 0.564705882352941 },
    CONTROL: { r: 0.564705882352941, g: 0.933333333333333, b: 0.749019607843137 },
    MOVEMENT: { r: 0.749019607843137, g: 0.933333333333333, b: 0.564705882352941 },
    DEFENSE: { r: 0.564705882352941, g: 0.564705882352941, b: 0.933333333333333 },
    ATTACK: { r: 0.435294117647059, g: 0.0666666666666667, b: 0.435294117647059 }
  },
  17: {
    name: "Digital Ecosystem 17",
    category: "Digital Ecosystem",
    description: "Generated palette based on color theory",
    CORE: { r: 0.980392156862745, g: 0.603921568627451, b: 0.980392156862745 },
    CONTROL: { r: 0.980392156862745, g: 0.603921568627451, b: 0.792156862745098 },
    MOVEMENT: { r: 0.792156862745098, g: 0.603921568627451, b: 0.980392156862745 },
    DEFENSE: { r: 0.980392156862745, g: 0.980392156862745, b: 0.603921568627451 },
    ATTACK: { r: 0.0196078431372549, g: 0.396078431372549, b: 0.0196078431372549 }
  },
  26: {
    name: "Seasonal Themes 26",
    category: "Seasonal Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.294117647058824, g: 0.384313725490196, b: 0.0274509803921569 },
    CONTROL: { r: 0.117647058823529, g: 0.384313725490196, b: 0.0274509803921569 },
    MOVEMENT: { r: 0.384313725490196, g: 0.298039215686275, b: 0.0274509803921569 },
    DEFENSE: { r: 0.0274509803921569, g: 0.294117647058824, b: 0.384313725490196 },
    ATTACK: { r: 0.705882352941177, g: 0.615686274509804, b: 0.972549019607843 }
  },
  13: {
    name: "Emotional Themes 13",
    category: "Emotional Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.964705882352941, g: 0.482352941176471, b: 0.733333333333333 },
    CONTROL: { r: 0.964705882352941, g: 0.482352941176471, b: 0.490196078431373 },
    MOVEMENT: { r: 0.956862745098039, g: 0.482352941176471, b: 0.964705882352941 },
    DEFENSE: { r: 0.733333333333333, g: 0.964705882352941, b: 0.482352941176471 },
    ATTACK: { r: 0.0352941176470588, g: 0.517647058823529, b: 0.266666666666667 }
  },
  27: {
    name: "Emotional Themes 27",
    category: "Emotional Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.305882352941176, g: 0.164705882352941, b: 0.0431372549019608 },
    CONTROL: { r: 0.305882352941176, g: 0.298039215686275, b: 0.0431372549019608 },
    MOVEMENT: { r: 0.305882352941176, g: 0.0431372549019608, b: 0.0549019607843137 },
    DEFENSE: { r: 0.0431372549019608, g: 0.305882352941176, b: 0.164705882352941 },
    ATTACK: { r: 0.694117647058824, g: 0.835294117647059, b: 0.956862745098039 }
  },
  30: {
    name: "Cosmic Voyage 30",
    category: "Cosmic Voyage",
    description: "Generated palette based on color theory",
    CORE: { r: 0.505882352941176, g: 0.823529411764706, b: 0.0784313725490196 },
    CONTROL: { r: 0.133333333333333, g: 0.823529411764706, b: 0.0784313725490196 },
    MOVEMENT: { r: 0.823529411764706, g: 0.768627450980392, b: 0.0784313725490196 },
    DEFENSE: { r: 0.0784313725490196, g: 0.505882352941176, b: 0.823529411764706 },
    ATTACK: { r: 0.494117647058824, g: 0.176470588235294, b: 0.92156862745098 }
  },
  18: {
    name: "Natural Themes 18",
    category: "Natural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.227450980392157, g: 0.254901960784314, b: 0.647058823529412 },
    CONTROL: { r: 0.407843137254902, g: 0.227450980392157, b: 0.647058823529412 },
    MOVEMENT: { r: 0.227450980392157, g: 0.466666666666667, b: 0.647058823529412 },
    DEFENSE: { r: 0.647058823529412, g: 0.227450980392157, b: 0.254901960784314 },
    ATTACK: { r: 0.772549019607843, g: 0.745098039215686, b: 0.352941176470588 }
  },
  36: {
    name: "Bitcoin-Inspired 36",
    category: "Bitcoin-Inspired",
    description: "Generated palette based on color theory",
    CORE: { r: 0.117647058823529, g: 0.247058823529412, b: 0.282352941176471 },
    CONTROL: { r: 0.117647058823529, g: 0.164705882352941, b: 0.282352941176471 },
    MOVEMENT: { r: 0.117647058823529, g: 0.282352941176471, b: 0.235294117647059 },
    DEFENSE: { r: 0.282352941176471, g: 0.117647058823529, b: 0.247058823529412 },
    ATTACK: { r: 0.882352941176471, g: 0.752941176470588, b: 0.717647058823529 }
  },
  bitcoinGold: {
    name: "Bitcoin Gold",
    category: "Bitcoin-Inspired",
    description: "Generated palette based on color theory",
    CORE: { r: 1, g: 0.843137254901961, b: 0 },
    CONTROL: { r: 0.654901960784314, g: 1, b: 0 },
    MOVEMENT: { r: 1, g: 0.345098039215686, b: 0 },
    DEFENSE: { r: 0, g: 1, b: 0.843137254901961 },
    ATTACK: { r: 0, g: 0.156862745098039, b: 1 }
  },
  digitalMatrix: {
    name: "Digital Matrix",
    category: "Digital Ecosystem",
    description: "Generated palette based on color theory",
    CORE: { r: 0, g: 1, b: 0 },
    CONTROL: { r: 0, g: 1, b: 0.501960784313725 },
    MOVEMENT: { r: 0.501960784313725, g: 1, b: 0 },
    DEFENSE: { r: 0, g: 0, b: 1 },
    ATTACK: { r: 1, g: 0, b: 1 }
  },
  29: {
    name: "Bitcoin-Inspired 29",
    category: "Bitcoin-Inspired",
    description: "Generated palette based on color theory",
    CORE: { r: 0.172549019607843, g: 0.619607843137255, b: 0.92156862745098 },
    CONTROL: { r: 0.172549019607843, g: 0.247058823529412, b: 0.92156862745098 },
    MOVEMENT: { r: 0.172549019607843, g: 0.92156862745098, b: 0.847058823529412 },
    DEFENSE: { r: 0.92156862745098, g: 0.172549019607843, b: 0.619607843137255 },
    ATTACK: { r: 0.827450980392157, g: 0.380392156862745, b: 0.0784313725490196 }
  },
  23: {
    name: "Cosmic Voyage 23",
    category: "Cosmic Voyage",
    description: "Generated palette based on color theory",
    CORE: { r: 0.352941176470588, g: 0.384313725490196, b: 0.56078431372549 },
    CONTROL: { r: 0.427450980392157, g: 0.352941176470588, b: 0.56078431372549 },
    MOVEMENT: { r: 0.352941176470588, g: 0.490196078431373, b: 0.56078431372549 },
    DEFENSE: { r: 0.56078431372549, g: 0.352941176470588, b: 0.384313725490196 },
    ATTACK: { r: 0.647058823529412, g: 0.615686274509804, b: 0.43921568627451 }
  },
  naturalOcean: {
    name: "Natural Ocean",
    category: "Natural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0, g: 0.411764705882353, b: 0.580392156862745 },
    CONTROL: { r: 0, g: 0.12156862745098, b: 0.580392156862745 },
    MOVEMENT: { r: 0, g: 0.580392156862745, b: 0.458823529411765 },
    DEFENSE: { r: 0.580392156862745, g: 0, b: 0.411764705882353 },
    ATTACK: { r: 1, g: 0.588235294117647, b: 0.419607843137255 }
  },
  1: {
    name: "Bitcoin-Inspired 1",
    category: "Bitcoin-Inspired",
    description: "Generated palette based on color theory",
    CORE: { r: 0.0705882352941176, g: 0.552941176470588, b: 0.956862745098039 },
    CONTROL: { r: 0.0705882352941176, g: 0.109803921568627, b: 0.956862745098039 },
    MOVEMENT: { r: 0.0705882352941176, g: 0.956862745098039, b: 0.917647058823529 },
    DEFENSE: { r: 0.956862745098039, g: 0.0705882352941176, b: 0.552941176470588 },
    ATTACK: { r: 0.929411764705882, g: 0.447058823529412, b: 0.0431372549019608 }
  },
  naturalForest: {
    name: "Natural Forest",
    category: "Natural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.133333333333333, g: 0.545098039215686, b: 0.133333333333333 },
    CONTROL: { r: 0.133333333333333, g: 0.545098039215686, b: 0.341176470588235 },
    MOVEMENT: { r: 0.341176470588235, g: 0.545098039215686, b: 0.133333333333333 },
    DEFENSE: { r: 0.133333333333333, g: 0.133333333333333, b: 0.545098039215686 },
    ATTACK: { r: 0.866666666666667, g: 0.454901960784314, b: 0.866666666666667 }
  },
  5: {
    name: "Seasonal Themes 5",
    category: "Seasonal Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.764705882352941, g: 0.0784313725490196, b: 0.792156862745098 },
    CONTROL: { r: 0.792156862745098, g: 0.0784313725490196, b: 0.462745098039216 },
    MOVEMENT: { r: 0.407843137254902, g: 0.0784313725490196, b: 0.792156862745098 },
    DEFENSE: { r: 0.792156862745098, g: 0.764705882352941, b: 0.0784313725490196 },
    ATTACK: { r: 0.235294117647059, g: 0.92156862745098, b: 0.207843137254902 }
  },
  4: {
    name: "Natural Themes 4",
    category: "Natural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.835294117647059, g: 0.682352941176471, b: 0.627450980392157 },
    CONTROL: { r: 0.835294117647059, g: 0.788235294117647, b: 0.627450980392157 },
    MOVEMENT: { r: 0.835294117647059, g: 0.627450980392157, b: 0.674509803921569 },
    DEFENSE: { r: 0.627450980392157, g: 0.835294117647059, b: 0.682352941176471 },
    ATTACK: { r: 0.164705882352941, g: 0.317647058823529, b: 0.372549019607843 }
  },
  24: {
    name: "Digital Ecosystem 24",
    category: "Digital Ecosystem",
    description: "Generated palette based on color theory",
    CORE: { r: 0.674509803921569, g: 0.513725490196078, b: 0.376470588235294 },
    CONTROL: { r: 0.674509803921569, g: 0.662745098039216, b: 0.376470588235294 },
    MOVEMENT: { r: 0.674509803921569, g: 0.376470588235294, b: 0.388235294117647 },
    DEFENSE: { r: 0.376470588235294, g: 0.674509803921569, b: 0.513725490196078 },
    ATTACK: { r: 0.325490196078431, g: 0.486274509803922, b: 0.623529411764706 }
  },
  3: {
    name: "Digital Ecosystem 3",
    category: "Digital Ecosystem",
    description: "Generated palette based on color theory",
    CORE: { r: 0.725490196078431, g: 0.125490196078431, b: 0.176470588235294 },
    CONTROL: { r: 0.725490196078431, g: 0.376470588235294, b: 0.125490196078431 },
    MOVEMENT: { r: 0.725490196078431, g: 0.125490196078431, b: 0.47843137254902 },
    DEFENSE: { r: 0.176470588235294, g: 0.725490196078431, b: 0.125490196078431 },
    ATTACK: { r: 0.274509803921569, g: 0.874509803921569, b: 0.823529411764706 }
  },
  39: {
    name: "Natural Themes 39",
    category: "Natural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.466666666666667, g: 0.580392156862745, b: 0.243137254901961 },
    CONTROL: { r: 0.298039215686275, g: 0.580392156862745, b: 0.243137254901961 },
    MOVEMENT: { r: 0.580392156862745, g: 0.525490196078431, b: 0.243137254901961 },
    DEFENSE: { r: 0.243137254901961, g: 0.466666666666667, b: 0.580392156862745 },
    ATTACK: { r: 0.533333333333333, g: 0.419607843137255, b: 0.756862745098039 }
  },
  14: {
    name: "Cultural Themes 14",
    category: "Cultural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.0156862745098039, g: 0.149019607843137, b: 0.588235294117647 },
    CONTROL: { r: 0.168627450980392, g: 0.0156862745098039, b: 0.588235294117647 },
    MOVEMENT: { r: 0.0156862745098039, g: 0.435294117647059, b: 0.588235294117647 },
    DEFENSE: { r: 0.588235294117647, g: 0.0156862745098039, b: 0.149019607843137 },
    ATTACK: { r: 0.984313725490196, g: 0.850980392156863, b: 0.411764705882353 }
  },
  37: {
    name: "Cosmic Voyage 37",
    category: "Cosmic Voyage",
    description: "Generated palette based on color theory",
    CORE: { r: 0.56078431372549, g: 0.105882352941176, b: 0.270588235294118 },
    CONTROL: { r: 0.56078431372549, g: 0.168627450980392, b: 0.105882352941176 },
    MOVEMENT: { r: 0.56078431372549, g: 0.105882352941176, b: 0.498039215686275 },
    DEFENSE: { r: 0.270588235294118, g: 0.56078431372549, b: 0.105882352941176 },
    ATTACK: { r: 0.43921568627451, g: 0.894117647058824, b: 0.729411764705882 }
  },
  22: {
    name: "Bitcoin-Inspired 22",
    category: "Bitcoin-Inspired",
    description: "Generated palette based on color theory",
    CORE: { r: 0.980392156862745, g: 0.572549019607843, b: 0.52156862745098 },
    CONTROL: { r: 0.980392156862745, g: 0.8, b: 0.52156862745098 },
    MOVEMENT: { r: 0.980392156862745, g: 0.52156862745098, b: 0.698039215686274 },
    DEFENSE: { r: 0.52156862745098, g: 0.980392156862745, b: 0.572549019607843 },
    ATTACK: { r: 0.0196078431372549, g: 0.427450980392157, b: 0.47843137254902 }
  },
  28: {
    name: "Cultural Themes 28",
    category: "Cultural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.627450980392157, g: 0.286274509803922, b: 0.854901960784314 },
    CONTROL: { r: 0.854901960784314, g: 0.286274509803922, b: 0.8 },
    MOVEMENT: { r: 0.341176470588235, g: 0.286274509803922, b: 0.854901960784314 },
    DEFENSE: { r: 0.854901960784314, g: 0.627450980392157, b: 0.286274509803922 },
    ATTACK: { r: 0.372549019607843, g: 0.713725490196078, b: 0.145098039215686 }
  },
  bitcoinEarth: {
    name: "Bitcoin Earth",
    category: "Bitcoin-Inspired",
    description: "Generated palette based on color theory",
    CORE: { r: 0.823529411764706, g: 0.411764705882353, b: 0.117647058823529 },
    CONTROL: { r: 0.823529411764706, g: 0.764705882352941, b: 0.117647058823529 },
    MOVEMENT: { r: 0.823529411764706, g: 0.117647058823529, b: 0.176470588235294 },
    DEFENSE: { r: 0.117647058823529, g: 0.823529411764706, b: 0.411764705882353 },
    ATTACK: { r: 0.176470588235294, g: 0.588235294117647, b: 0.882352941176471 }
  },
  25: {
    name: "Natural Themes 25",
    category: "Natural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.258823529411765, g: 0.752941176470588, b: 0.219607843137255 },
    CONTROL: { r: 0.219607843137255, g: 0.752941176470588, b: 0.447058823529412 },
    MOVEMENT: { r: 0.525490196078431, g: 0.752941176470588, b: 0.219607843137255 },
    DEFENSE: { r: 0.219607843137255, g: 0.258823529411765, b: 0.752941176470588 },
    ATTACK: { r: 0.741176470588235, g: 0.247058823529412, b: 0.780392156862745 }
  },
  20: {
    name: "Emotional Themes 20",
    category: "Emotional Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.403921568627451, g: 0.168627450980392, b: 0.0352941176470588 },
    CONTROL: { r: 0.403921568627451, g: 0.352941176470588, b: 0.0352941176470588 },
    MOVEMENT: { r: 0.403921568627451, g: 0.0352941176470588, b: 0.0862745098039216 },
    DEFENSE: { r: 0.0352941176470588, g: 0.403921568627451, b: 0.168627450980392 },
    ATTACK: { r: 0.596078431372549, g: 0.831372549019608, b: 0.964705882352941 }
  },
  digitalNeon: {
    name: "Digital Neon",
    category: "Digital Ecosystem",
    description: "Generated palette based on color theory",
    CORE: { r: 1, g: 0, b: 1 },
    CONTROL: { r: 1, g: 0, b: 0.501960784313725 },
    MOVEMENT: { r: 0.501960784313725, g: 0, b: 1 },
    DEFENSE: { r: 1, g: 1, b: 0 },
    ATTACK: { r: 0, g: 1, b: 0 }
  },
  15: {
    name: "Bitcoin-Inspired 15",
    category: "Bitcoin-Inspired",
    description: "Generated palette based on color theory",
    CORE: { r: 0.0549019607843137, g: 0.0352941176470588, b: 0.0235294117647059 },
    CONTROL: { r: 0.0549019607843137, g: 0.0509803921568627, b: 0.0235294117647059 },
    MOVEMENT: { r: 0.0549019607843137, g: 0.0235294117647059, b: 0.0274509803921569 },
    DEFENSE: { r: 0.0235294117647059, g: 0.0549019607843137, b: 0.0352941176470588 },
    ATTACK: { r: 0.945098039215686, g: 0.964705882352941, b: 0.976470588235294 }
  },
  33: {
    name: "Seasonal Themes 33",
    category: "Seasonal Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.803921568627451, g: 0.968627450980392, b: 0.109803921568627 },
    CONTROL: { r: 0.376470588235294, g: 0.968627450980392, b: 0.109803921568627 },
    MOVEMENT: { r: 0.968627450980392, g: 0.705882352941177, b: 0.109803921568627 },
    DEFENSE: { r: 0.109803921568627, g: 0.803921568627451, b: 0.968627450980392 },
    ATTACK: { r: 0.196078431372549, g: 0.0313725490196078, b: 0.890196078431372 }
  },
  21: {
    name: "Cultural Themes 21",
    category: "Cultural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.725490196078431, g: 0.650980392156863, b: 0.541176470588235 },
    CONTROL: { r: 0.709803921568627, g: 0.725490196078431, b: 0.541176470588235 },
    MOVEMENT: { r: 0.725490196078431, g: 0.56078431372549, b: 0.541176470588235 },
    DEFENSE: { r: 0.541176470588235, g: 0.725490196078431, b: 0.650980392156863 },
    ATTACK: { r: 0.274509803921569, g: 0.349019607843137, b: 0.458823529411765 }
  },
  19: {
    name: "Seasonal Themes 19",
    category: "Seasonal Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.890196078431372, g: 0.949019607843137, b: 0.192156862745098 },
    CONTROL: { r: 0.509803921568627, g: 0.949019607843137, b: 0.192156862745098 },
    MOVEMENT: { r: 0.949019607843137, g: 0.631372549019608, b: 0.192156862745098 },
    DEFENSE: { r: 0.192156862745098, g: 0.890196078431372, b: 0.949019607843137 },
    ATTACK: { r: 0.109803921568627, g: 0.0509803921568627, b: 0.807843137254902 }
  },
  cosmicNebula: {
    name: "Cosmic Nebula",
    category: "Cosmic Voyage",
    description: "Generated palette based on color theory",
    CORE: { r: 0.482352941176471, g: 0.12156862745098, b: 0.635294117647059 },
    CONTROL: { r: 0.635294117647059, g: 0.12156862745098, b: 0.533333333333333 },
    MOVEMENT: { r: 0.227450980392157, g: 0.12156862745098, b: 0.635294117647059 },
    DEFENSE: { r: 0.635294117647059, g: 0.482352941176471, b: 0.12156862745098 },
    ATTACK: { r: 0.517647058823529, g: 0.87843137254902, b: 0.364705882352941 }
  },
  9: {
    name: "Cosmic Voyage 9",
    category: "Cosmic Voyage",
    description: "Generated palette based on color theory",
    CORE: { r: 0.431372549019608, g: 0.105882352941176, b: 0.349019607843137 },
    CONTROL: { r: 0.431372549019608, g: 0.105882352941176, b: 0.184313725490196 },
    MOVEMENT: { r: 0.352941176470588, g: 0.105882352941176, b: 0.431372549019608 },
    DEFENSE: { r: 0.349019607843137, g: 0.431372549019608, b: 0.105882352941176 },
    ATTACK: { r: 0.568627450980392, g: 0.894117647058824, b: 0.650980392156863 }
  },
  cosmicStardust: {
    name: "Cosmic Stardust",
    category: "Cosmic Voyage",
    description: "Generated palette based on color theory",
    CORE: { r: 0, g: 0.749019607843137, b: 1 },
    CONTROL: { r: 0, g: 0.250980392156863, b: 1 },
    MOVEMENT: { r: 0, g: 1, b: 0.749019607843137 },
    DEFENSE: { r: 1, g: 0, b: 0.749019607843137 },
    ATTACK: { r: 1, g: 0.250980392156863, b: 0 }
  },
  16: {
    name: "Cosmic Voyage 16",
    category: "Cosmic Voyage",
    description: "Generated palette based on color theory",
    CORE: { r: 0.831372549019608, g: 0.87843137254902, b: 0.494117647058824 },
    CONTROL: { r: 0.63921568627451, g: 0.87843137254902, b: 0.494117647058824 },
    MOVEMENT: { r: 0.87843137254902, g: 0.733333333333333, b: 0.494117647058824 },
    DEFENSE: { r: 0.494117647058824, g: 0.831372549019608, b: 0.87843137254902 },
    ATTACK: { r: 0.168627450980392, g: 0.12156862745098, b: 0.505882352941176 }
  },
  35: {
    name: "Cultural Themes 35",
    category: "Cultural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.705882352941177, g: 0.254901960784314, b: 0.0392156862745098 },
    CONTROL: { r: 0.705882352941177, g: 0.588235294117647, b: 0.0392156862745098 },
    MOVEMENT: { r: 0.705882352941177, g: 0.0392156862745098, b: 0.156862745098039 },
    DEFENSE: { r: 0.0392156862745098, g: 0.705882352941177, b: 0.254901960784314 },
    ATTACK: { r: 0.294117647058824, g: 0.745098039215686, b: 0.96078431372549 }
  },
  32: {
    name: "Natural Themes 32",
    category: "Natural Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.803921568627451, g: 0.435294117647059, b: 0.0431372549019608 },
    CONTROL: { r: 0.792156862745098, g: 0.803921568627451, b: 0.0431372549019608 },
    MOVEMENT: { r: 0.803921568627451, g: 0.0549019607843137, b: 0.0431372549019608 },
    DEFENSE: { r: 0.0431372549019608, g: 0.803921568627451, b: 0.435294117647059 },
    ATTACK: { r: 0.196078431372549, g: 0.564705882352941, b: 0.956862745098039 }
  },
  8: {
    name: "Bitcoin-Inspired 8",
    category: "Bitcoin-Inspired",
    description: "Generated palette based on color theory",
    CORE: { r: 0.435294117647059, g: 0.380392156862745, b: 0.176470588235294 },
    CONTROL: { r: 0.36078431372549, g: 0.435294117647059, b: 0.176470588235294 },
    MOVEMENT: { r: 0.435294117647059, g: 0.250980392156863, b: 0.176470588235294 },
    DEFENSE: { r: 0.176470588235294, g: 0.435294117647059, b: 0.380392156862745 },
    ATTACK: { r: 0.564705882352941, g: 0.619607843137255, b: 0.823529411764706 }
  },
  2: {
    name: "Cosmic Voyage 2",
    category: "Cosmic Voyage",
    description: "Generated palette based on color theory",
    CORE: { r: 0.925490196078431, g: 0.823529411764706, b: 0.356862745098039 },
    CONTROL: { r: 0.741176470588235, g: 0.925490196078431, b: 0.356862745098039 },
    MOVEMENT: { r: 0.925490196078431, g: 0.541176470588235, b: 0.356862745098039 },
    DEFENSE: { r: 0.356862745098039, g: 0.925490196078431, b: 0.823529411764706 },
    ATTACK: { r: 0.0745098039215686, g: 0.176470588235294, b: 0.643137254901961 }
  },
  34: {
    name: "Emotional Themes 34",
    category: "Emotional Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.47843137254902, g: 0.372549019607843, b: 0.2 },
    CONTROL: { r: 0.443137254901961, g: 0.47843137254902, b: 0.2 },
    MOVEMENT: { r: 0.47843137254902, g: 0.231372549019608, b: 0.2 },
    DEFENSE: { r: 0.2, g: 0.47843137254902, b: 0.372549019607843 },
    ATTACK: { r: 0.52156862745098, g: 0.627450980392157, b: 0.8 }
  },
  seasonalAutumn: {
    name: "Seasonal Autumn",
    category: "Seasonal Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.823529411764706, g: 0.411764705882353, b: 0.117647058823529 },
    CONTROL: { r: 0.823529411764706, g: 0.764705882352941, b: 0.117647058823529 },
    MOVEMENT: { r: 0.823529411764706, g: 0.117647058823529, b: 0.176470588235294 },
    DEFENSE: { r: 0.117647058823529, g: 0.823529411764706, b: 0.411764705882353 },
    ATTACK: { r: 0.176470588235294, g: 0.588235294117647, b: 0.882352941176471 }
  },
  6: {
    name: "Emotional Themes 6",
    category: "Emotional Themes",
    description: "Generated palette based on color theory",
    CORE: { r: 0.184313725490196, g: 0.129411764705882, b: 0.376470588235294 },
    CONTROL: { r: 0.309803921568627, g: 0.129411764705882, b: 0.376470588235294 },
    MOVEMENT: { r: 0.129411764705882, g: 0.2, b: 0.376470588235294 },
    DEFENSE: { r: 0.376470588235294, g: 0.184313725490196, b: 0.129411764705882 },
    ATTACK: { r: 0.815686274509804, g: 0.870588235294118, b: 0.623529411764706 }
  },
  31: {
    name: "Digital Ecosystem 31",
    category: "Digital Ecosystem",
    description: "Generated palette based on color theory",
    CORE: { r: 0.219607843137255, g: 0.215686274509804, b: 0.917647058823529 },
    CONTROL: { r: 0.572549019607843, g: 0.215686274509804, b: 0.917647058823529 },
    MOVEMENT: { r: 0.215686274509804, g: 0.564705882352941, b: 0.917647058823529 },
    DEFENSE: { r: 0.917647058823529, g: 0.219607843137255, b: 0.215686274509804 },
    ATTACK: { r: 0.780392156862745, g: 0.784313725490196, b: 0.0823529411764706 }
  },
};

/**
 * Get a palette by name
 */
export function getPalette(name: string): Palette {
  return COLOR_PALETTES[name] || COLOR_PALETTES.bitcoinClassic;
}

/**
 * Get all palettes
 */
export function getAllPalettes(): Palette[] {
  return Object.values(COLOR_PALETTES);
}

/**
 * Get palettes by category
 */
export function getPalettesByCategory(category: string): Palette[] {
  return Object.values(COLOR_PALETTES).filter(palette => palette.category === category);
}
